### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by amiltonwong** [drnikolaev/cvmlib#1]
Hi, @drnikolaev ,

I came accross the following error: 
# 

Compiling debug: srmatrix.cpp
Compiling debug: utils.cpp
Linking: ../../lib/libcvm_ia32_debug.so
/usr/bin/ld: cannot find -lblas_ia32_debug
/usr/bin/ld: cannot find -llapack_ia32_debug
collect2: error: ld returned 1 exit status
make[1]: **\* [../../lib/libcvm_ia32_debug.so] Error 1
make[1]: Leaving directory `/data/code/cvmlib/cvm/src'
make: **\* [debug] Error 2
root@milton-OptiPlex-9010:/data/code/cvmlib/cvm# 
# 

It shows that "blas_ia32_debug" & "lapack_ia32_debug" cannot be found. Could you suggest me how to fix it?

My system is ubuntu 14.04 (64bit)

Thanks~
Milton

**Comment by drnikolaev** [comment]
Hi @amiltonwong,
Pre-built static libs are here: https://github.com/drnikolaev/cvmlib/tree/cvmlib_v8.2/lib/linux/gf
Few questions: 
- What branch are you using? Master or cvmlib_8.2? I recommend cvmlib_8.2, although it's still under development.
- Since you are on 64-bit Linux, why wouldn't you build 64-bit version of the library?
- Could you paste exact command line you execute?

Thank you.

**Comment by amiltonwong** [comment]
Him, @drnikolaev ,
Thanks for your reply.

Now I switch to build v8.2.

Here is my exact commands I used:
$ git clone https://github.com/drnikolaev/cvmlib.git -b cvmlib_v8.2
$ cd cvmlib/cvm
$ make

The following are the output: 

root@milton-ThinkPad-T450:~/cvmlib/cvm# make
make debug -C ftn EM64T=1 GF_BLAS=1
make[1]: Entering directory `/root/cvmlib/cvm/ftn'
Compiling debug: axpym.f
Compiling debug: cmexp.f
Compiling debug: cmplx.f
Compiling debug: copym.f
Compiling debug: cpoly.f
Compiling debug: dmexp.f
Compiling debug: dpoly.f
Compiling debug: infnm.f
Compiling debug: npoly.f
Compiling debug: scalm.f
Compiling debug: smexp.f
Compiling debug: spoly.f
Compiling debug: zmexp.f
Compiling debug: zpoly.f
Compiling debug: icamax.f
Compiling debug: icamin.f
Compiling debug: idamax.f
Compiling debug: idamin.f
Compiling debug: isamax.f
Compiling debug: isamin.f
Compiling debug: izamax.f
Compiling debug: izamin.f
Archiving: ../../lib64/libftn_em64t_debug.a
make[1]: Leaving directory`/root/cvmlib/cvm/ftn'
make debug -C src EM64T=1 GF_BLAS=1
make[1]: Entering directory `/root/cvmlib/cvm/src'
Compiling debug: arrays.cpp
Compiling debug: cmatrix.cpp
Compiling debug: cvector.cpp
Compiling debug: globals.cpp
Compiling debug: rmatrix.cpp
Compiling debug: rvector.cpp
Compiling debug: scmatrix.cpp
Compiling debug: srmatrix.cpp
Compiling debug: utils.cpp
Archiving: ../../lib64/libcvm_em64t_debug.a
Compiling debug: arrays.cpp
Compiling debug: cmatrix.cpp
Compiling debug: cvector.cpp
Compiling debug: globals.cpp
Compiling debug: rmatrix.cpp
Compiling debug: rvector.cpp
Compiling debug: scmatrix.cpp
Compiling debug: srmatrix.cpp
Compiling debug: utils.cpp
Linking: ../../lib64/libcvm_em64t_debug.so
make[1]: Leaving directory`/root/cvmlib/cvm/src'
make debug -C test EM64T=1 GF_BLAS=1
make[1]: Entering directory `/root/cvmlib/cvm/test'
Compiling: testBlas.cpp
Compiling: testFunctional.cpp
Compiling: testInitialization.cpp
In file included from /usr/include/gtest/gtest.h:1807:0,
                 from test.h:14,
                 from testInitialization.cpp:10:
testInitialization.cpp: In member function ‘virtual void InitializationTest_TestVectorItr_Test<gtest_TypeParam_>::TestBody()’:
testInitialization.cpp:267:22: error: ‘max_element’ is not a member of ‘std’
     EXPECT_EQ(10. , *std::max_element(vs1.begin(), vs1.end())) << "rvector.max_element";
                      ^
testInitialization.cpp:269:5: error: ‘sort’ is not a member of ‘std’
     std::sort(vs1.begin(), vs1.end());
     ^
testInitialization.cpp:272:5: error: ‘reverse’ is not a member of ‘std’
     std::reverse(vs1.begin(), vs1.end());
     ^
make[1]: *** [dobj/testInitialization.o] Error 1
make[1]: Leaving directory`/root/cvmlib/cvm/test'
make: **\* [debug] Error 2
root@milton-ThinkPad-T450:~/cvmlib/cvm#

**Comment by amiltonwong** [comment]
Any package are pre-requisite? Intel MKL?

**Comment by drnikolaev** [comment]
No, MKL is optional. You can use either native BLAS/LAPACK or MKL. I pasted my output below, it builds and runs fine. So, I suspect some environment issues. Seems like you have `gtest` library installed somewhere else or it has different version. Could you please run `pull_gtest.sh` script like I did below?

``` bash
sam@ubuntu:~$ mkdir cvmlib_test
sam@ubuntu:~$ cd cvmlib_test/
sam@ubuntu:~/cvmlib_test$ git clone https://github.com/drnikolaev/cvmlib.git -b cvmlib_v8.2
Cloning into 'cvmlib'...
remote: Counting objects: 1728, done.
remote: Total 1728 (delta 0), reused 0 (delta 0), pack-reused 1728
Receiving objects: 100% (1728/1728), 193.24 MiB | 1.07 MiB/s, done.
Resolving deltas: 100% (966/966), done.
Checking connectivity... done.
sam@ubuntu:~/cvmlib_test$ cd cvmlib/cvm/
sam@ubuntu:~/cvmlib_test/cvmlib/cvm$ make
make debug -C ftn EM64T=1 GF_BLAS=1
make[1]: Entering directory '/home/sam/cvmlib_test/cvmlib/cvm/ftn'
Compiling debug: zmexp.f
Compiling debug: infnm.f
Compiling debug: dmexp.f
Compiling debug: zpoly.f
Compiling debug: axpym.f
Compiling debug: spoly.f
Compiling debug: copym.f
Compiling debug: npoly.f
Compiling debug: cmplx.f
Compiling debug: dpoly.f
Compiling debug: cpoly.f
Compiling debug: smexp.f
Compiling debug: scalm.f
Compiling debug: cmexp.f
Compiling debug: icamin.f
Compiling debug: isamax.f
Compiling debug: izamin.f
Compiling debug: icamax.f
Compiling debug: idamin.f
Compiling debug: izamax.f
Compiling debug: idamax.f
Compiling debug: isamin.f
Archiving: ../../lib64/libftn_em64t_debug.a
make[1]: Leaving directory '/home/sam/cvmlib_test/cvmlib/cvm/ftn'
make debug -C src EM64T=1 GF_BLAS=1
make[1]: Entering directory '/home/sam/cvmlib_test/cvmlib/cvm/src'
Compiling debug: utils.cpp
Compiling debug: rmatrix.cpp
Compiling debug: arrays.cpp
Compiling debug: cvector.cpp
Compiling debug: globals.cpp
Compiling debug: cmatrix.cpp
Compiling debug: rvector.cpp
Compiling debug: scmatrix.cpp
Compiling debug: srmatrix.cpp
Archiving: ../../lib64/libcvm_em64t_debug.a
Compiling debug: utils.cpp
Compiling debug: rmatrix.cpp
Compiling debug: arrays.cpp
Compiling debug: cvector.cpp
Compiling debug: globals.cpp
Compiling debug: cmatrix.cpp
Compiling debug: rvector.cpp
Compiling debug: scmatrix.cpp
Compiling debug: srmatrix.cpp
Linking: ../../lib64/libcvm_em64t_debug.so
make[1]: Leaving directory '/home/sam/cvmlib_test/cvmlib/cvm/src'
make debug -C test EM64T=1 GF_BLAS=1
make[1]: Entering directory '/home/sam/cvmlib_test/cvmlib/cvm/test'
Compiling: testInitialization.cpp
In file included from testInitialization.cpp:10:0:
test.h:14:25: fatal error: gtest/gtest.h: No such file or directory
compilation terminated.
Makefile:161: recipe for target 'dobj/testInitialization.o' failed
make[1]: *** [dobj/testInitialization.o] Error 1
make[1]: Leaving directory '/home/sam/cvmlib_test/cvmlib/cvm/test'
Makefile:12: recipe for target 'debug' failed
make: *** [debug] Error 2
sam@ubuntu:~/cvmlib_test/cvmlib/cvm$ ls -al
total 236
drwxrwxr-x 10 sam sam   4096 Jul  5 10:43 .
drwxrwxr-x  8 sam sam   4096 Jul  5 10:43 ..
-rw-rw-r--  1 sam sam    847 Jul  5 10:43 build32mingw.sh
-rw-rw-r--  1 sam sam   1453 Jul  5 10:43 build64mingw.sh
-rw-rw-r--  1 sam sam   7605 Jul  5 10:43 cvmlib_2010.sln
-rw-rw-r--  1 sam sam   7605 Jul  5 10:43 cvmlib_2012.sln
-rw-rw-r--  1 sam sam   7684 Jul  5 10:43 cvmlib_2013.sln
-rw-rw-r--  1 sam sam   7569 Jul  5 10:43 cvmlib_2015.sln
drwxrwxr-x  4 sam sam   4096 Jul  5 10:43 doc
-rw-rw-r--  1 sam sam 108089 Jul  5 10:43 Doxyfile
drwxrwxr-x  2 sam sam   4096 Jul  5 10:43 doxygen
drwxrwxr-x  6 sam sam   4096 Jul  5 10:43 eclipse
drwxrwxr-x  3 sam sam   4096 Jul  5 10:45 ftn
-rw-rw-r--  1 sam sam   1521 Jul  5 10:43 INSTALL
-rwxrwxr-x  1 sam sam    704 Jul  5 10:43 lapack_build32.sh
-rwxrwxr-x  1 sam sam   1574 Jul  5 10:43 lapack_build64_mac.sh
-rwxrwxr-x  1 sam sam   1607 Jul  5 10:43 lapack_build64.sh
drwxrwxr-x  4 sam sam   4096 Jul  5 10:43 mac
-rw-rw-r--  1 sam sam    538 Jul  5 10:43 Makefile
-rwxrwxr-x  1 sam sam   1936 Jul  5 10:43 mkl_build32.sh
-rwxrwxr-x  1 sam sam   2419 Jul  5 10:43 mkl_build64_mac.sh
-rwxrwxr-x  1 sam sam   2715 Jul  5 10:43 mkl_build64.sh
drwxrwxr-x  4 sam sam   4096 Jul  5 10:45 src
drwxrwxr-x  4 sam sam   4096 Jul  5 10:45 test
-rw-rw-r--  1 sam sam   1408 Jul  5 10:43 test_2010.sln
-rw-rw-r--  1 sam sam   1406 Jul  5 10:43 test_2012.sln
-rw-rw-r--  1 sam sam   1406 Jul  5 10:43 test_2013.sln
-rw-rw-r--  1 sam sam   1755 Jul  5 10:43 test_2015.sln
drwxrwxr-x  2 sam sam   4096 Jul  5 10:43 test.old
sam@ubuntu:~/cvmlib_test/cvmlib/cvm$ cd ..
sam@ubuntu:~/cvmlib_test/cvmlib$ ls
cvm  gtest  lib  lib64  makes  pull_gtest.sh  README.md
sam@ubuntu:~/cvmlib_test/cvmlib$ ./pull_gtest.sh 
Submodule 'gtest' (https://github.com/google/googletest.git) registered for path 'gtest'
Cloning into 'gtest'...
remote: Counting objects: 7346, done.
remote: Total 7346 (delta 0), reused 0 (delta 0), pack-reused 7346
Receiving objects: 100% (7346/7346), 2.56 MiB | 520.00 KiB/s, done.
Resolving deltas: 100% (5469/5469), done.
Checking connectivity... done.
Submodule path 'gtest': checked out 'ff5ffd457e032c8be8a64a7a94c824063c8b11e3'
~/cvmlib_test/cvmlib/gtest ~/cvmlib_test/cvmlib
-- The C compiler identification is GNU 5.3.1
-- The CXX compiler identification is GNU 5.3.1
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PythonInterp: /usr/bin/python (found version "2.7.11") 
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Configuring done
-- Generating done
-- Build files have been written to: /home/sam/cvmlib_test/cvmlib/gtest
Scanning dependencies of target gtest
[ 50%] Building CXX object googlemock/gtest/CMakeFiles/gtest.dir/src/gtest-all.cc.o
[100%] Linking CXX static library libgtest.a
[100%] Built target gtest
~/cvmlib_test/cvmlib
sam@ubuntu:~/cvmlib_test/cvmlib$ cd cvm/
sam@ubuntu:~/cvmlib_test/cvmlib/cvm$ make
make debug -C ftn EM64T=1 GF_BLAS=1
make[1]: Entering directory '/home/sam/cvmlib_test/cvmlib/cvm/ftn'
make[1]: Nothing to be done for 'debug'.
make[1]: Leaving directory '/home/sam/cvmlib_test/cvmlib/cvm/ftn'
make debug -C src EM64T=1 GF_BLAS=1
make[1]: Entering directory '/home/sam/cvmlib_test/cvmlib/cvm/src'
make[1]: Nothing to be done for 'debug'.
make[1]: Leaving directory '/home/sam/cvmlib_test/cvmlib/cvm/src'
make debug -C test EM64T=1 GF_BLAS=1
make[1]: Entering directory '/home/sam/cvmlib_test/cvmlib/cvm/test'
Compiling: testInitialization.cpp
Compiling: testLapack.cpp
Compiling: testMisc.cpp
Compiling: testmain.cpp
Compiling: testFunctional.cpp
Compiling: testBlas.cpp
Linking: ../../lib64/regtest_cvm_em64t_debug
make[1]: Leaving directory '/home/sam/cvmlib_test/cvmlib/cvm/test'
make release -C ftn EM64T=1 GF_BLAS=1
make[1]: Entering directory '/home/sam/cvmlib_test/cvmlib/cvm/ftn'
Compiling release: zmexp.f
Compiling release: infnm.f
Compiling release: dmexp.f
Compiling release: zpoly.f
Compiling release: axpym.f
Compiling release: spoly.f
Compiling release: copym.f
Compiling release: npoly.f
Compiling release: cmplx.f
Compiling release: dpoly.f
Compiling release: cpoly.f
Compiling release: smexp.f
Compiling release: scalm.f
Compiling release: cmexp.f
Compiling release: icamin.f
Compiling release: isamax.f
Compiling release: izamin.f
Compiling release: icamax.f
Compiling release: idamin.f
Compiling release: izamax.f
Compiling release: idamax.f
Compiling release: isamin.f
Archiving: ../../lib64/libftn_em64t.a
make[1]: Leaving directory '/home/sam/cvmlib_test/cvmlib/cvm/ftn'
make release -C src EM64T=1 GF_BLAS=1
make[1]: Entering directory '/home/sam/cvmlib_test/cvmlib/cvm/src'
Compiling release: utils.cpp
Compiling release: rmatrix.cpp
Compiling release: arrays.cpp
Compiling release: cvector.cpp
Compiling release: globals.cpp
Compiling release: cmatrix.cpp
Compiling release: rvector.cpp
Compiling release: scmatrix.cpp
Compiling release: srmatrix.cpp
Archiving: ../../lib64/libcvm_em64t.a
Compiling release: utils.cpp
Compiling release: rmatrix.cpp
Compiling release: arrays.cpp
Compiling release: cvector.cpp
Compiling release: globals.cpp
Compiling release: cmatrix.cpp
Compiling release: rvector.cpp
Compiling release: scmatrix.cpp
Compiling release: srmatrix.cpp
Linking: ../../lib64/libcvm_em64t.so
make[1]: Leaving directory '/home/sam/cvmlib_test/cvmlib/cvm/src'
make release -C test EM64T=1 GF_BLAS=1
make[1]: Entering directory '/home/sam/cvmlib_test/cvmlib/cvm/test'
Compiling: testInitialization.cpp
Compiling: testLapack.cpp
Compiling: testMisc.cpp
Compiling: testmain.cpp
Compiling: testFunctional.cpp
Compiling: testBlas.cpp
Linking: ../../lib64/regtest_cvm_em64t
make[1]: Leaving directory '/home/sam/cvmlib_test/cvmlib/cvm/test'
sam@ubuntu:~/cvmlib_test/cvmlib/cvm$ cd ../lib64/
sam@ubuntu:~/cvmlib_test/cvmlib/lib64$ export LD_LIBRARY_PATH=.
sam@ubuntu:~/cvmlib_test/cvmlib/lib64$ ./regtest_cvm_em64t
[==========] Running 542 tests from 10 test cases.
[----------] Global test environment set-up.
[----------] 61 tests from InitializationTest/0, where TypeParam = float
[ RUN      ] InitializationTest/0.TestSizes
[       OK ] InitializationTest/0.TestSizes (0 ms)

...

[----------] Global test environment tear-down
[==========] 542 tests from 10 test cases ran. (761 ms total)
[  PASSED  ] 542 tests.
sam@ubuntu:~/cvmlib_test/cvmlib/lib64$ 
```

**Comment by drnikolaev** [comment]
@amiltonwong I just pushed a possible fix, could you try it please? I believe it was missing 

``` c++
#include <algorithm>
```

**Comment by amiltonwong** [comment]
@drnikolaev ,
Thank you so much for your kind help. I compile it successfully.
One more question: if I want to use cvm function in my practice code, let say:

# 

//test.cpp

#include "cvm.h"

int main() {
  cvm::rmatrix  mat1;
}

# 

What other approach I have to config in my system?

Thank~
Milton

**Comment by drnikolaev** [comment]
@amiltonwong great, thanks for confirming. The code snippet you mentioned requires to be linked with `lib64/libcvm_em64t.so` or `lib64/libcvm_em64t_debug.so` library, that's all. You can check `test/Makefile` as a reference. Good luck!

**Comment by amiltonwong** [comment]
Hi, @drnikolaev ,

Thanks for your reply, I solve it by adding the corresponding include path in my g++ option.

One more question, the following is my compile output after building a package (stereomapper) which requires cvm:
https://gist.github.com/amiltonwong/a959df31e8d3bf7ebfd4f6363c2099ee

But it seems there's conflict with current updated version of cvm. I remember the package (stereomapper) was released around 2011. Should I turn back to older version of cvm that released around 2011? Or any other suggestion?

Thanks~
Milton

**Comment by drnikolaev** [comment]
The link you provided shows bunch of errors caused by using older version of the language standard. All you need is `-std=c++0x` or `-std=c++11` switch to add. As of going back - try to use current release first. If it fails try to step back to older release, see cvmlib.com for details.

**Comment by AndreiBarsan** [comment]
Just in the hopes of it helping someone in the future, I, too was missing that flag and got confused for a while. If it's not there, then it's very likely that the true error message, namely "#error This file requires compiler and library support for the ISO C++ 2011 standard. This support is currently experimental, and must be enabled with the -std=c++11 or -std=gnu++11 compiler options." gets buried under A TON of seemingly unrelated type errors caused by (among other things) the failure of `using foo = bar` statements to parse. Hope this helps someone in the future!

**Comment by drnikolaev** [comment]
Yeah, agreed. Error number limiter might help here, need to think about it.

**Comment by drnikolaev** [comment]
Revamped all building scripts
